# api-deployment.yaml
apiVersion: apps/v1  # Deployment 리소스의 API 버전
kind: Deployment     # 만들려는 쿠버네티스 리소스의 종류: Deployment (애플리케이션을 배포하고 관리)
metadata:
  name: my-api-deployment # 이 Deployment의 이름
spec:
  replicas: 2          # 'replicas'는 복제본을 의미. 이 앱의 Pod를 2개 유지해라.
  selector:
    matchLabels:
      app: my-api      # 'app: my-api' 레이블을 가진 Pod를 관리하겠다.
  template:
    metadata:
      labels:
        app: my-api    # 이 Pod에 'app: my-api' 레이블을 붙인다. (selector와 일치해야 함)
    spec:
      containers:
      - name: my-api-container # 컨테이너의 이름
        image: my-api          # 4일차에 빌드한 도커 이미지 이름을 사용 (중요!)
        imagePullPolicy: Never # 로컬에 있는 이미지를 사용하겠다는 설정 (인터넷에서 다운받지 마라).
        ports:
        - containerPort: 8000 # 컨테이너 내부에서 노출할 포트